import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
month=[0, 4, 5, 8, 9, 12, 15, 18]
weight=[2.48, 6.4, 7.74, 8.8, 9.25, 9.74, 10.9, 11.4]
height=[50, 63, 68, 71, 74, 78, 81.5, 85]
head=[32, 39.5, 41.5, 43, 44, 45, 46, 46.5]
who_weight_data=pd.read_excel(r'D:\Documents\Growth Tracker Project\wfa-boys-0-2.xlsx', nrows=25)
who_weight_month_df=pd.DataFrame(who_weight_data, columns=['month'])
who_month=who_weight_month_df.to_numpy()
who_weigth_1st_df=pd.DataFrame(who_weight_data, columns=['1st'])
who_weigth_1st=who_weigth_1st_df.to_numpy()
who_weigth_3rd_df=pd.DataFrame(who_weight_data, columns=['3rd'])
who_weigth_3rd=who_weigth_3rd_df.to_numpy()
who_weigth_5th_df=pd.DataFrame(who_weight_data, columns=['5th'])
who_weigth_5th=who_weigth_5th_df.to_numpy()
who_weigth_15th_df=pd.DataFrame(who_weight_data, columns=['15th'])
who_weigth_15th=who_weigth_15th_df.to_numpy()
who_weigth_25th_df=pd.DataFrame(who_weight_data, columns=['25th'])
who_weigth_25th=who_weigth_25th_df.to_numpy()
who_weigth_50th_df=pd.DataFrame(who_weight_data, columns=['50th'])
who_weigth_50th=who_weigth_50th_df.to_numpy()
who_weigth_75th_df=pd.DataFrame(who_weight_data, columns=['75th'])
who_weigth_75th=who_weigth_75th_df.to_numpy()
who_weigth_85th_df=pd.DataFrame(who_weight_data, columns=['85th'])
who_weigth_85th=who_weigth_85th_df.to_numpy()
who_weigth_95th_df=pd.DataFrame(who_weight_data, columns=['95th'])
who_weigth_95th=who_weigth_95th_df.to_numpy()
who_weigth_97th_df=pd.DataFrame(who_weight_data, columns=['97th'])
who_weigth_97th=who_weigth_97th_df.to_numpy()
who_weigth_99th_df=pd.DataFrame(who_weight_data, columns=['99th'])
who_weigth_99th=who_weigth_99th_df.to_numpy()
plt.plot(month, weight, color='blue', linewidth=3, markevery=1, marker="o", label='Sepehr')
plt.plot(who_month, who_weigth_1st, color='red', linewidth=1.5, linestyle='dotted', label='1st')
plt.plot(who_month, who_weigth_3rd, color='brown', linewidth=1.5, linestyle='dotted', label='3rd')
plt.plot(who_month, who_weigth_5th, color='rosybrown', linewidth=1.5, linestyle='dotted', label='5th')
plt.plot(who_month, who_weigth_15th, color='orangered', linewidth=1.5, linestyle='dotted', label='15th')
plt.plot(who_month, who_weigth_25th, color='darkorange', linewidth=1.5, linestyle='dotted', label='25th')
plt.plot(who_month, who_weigth_50th, color='forestgreen', linewidth=1.5, linestyle='dotted', label='50th')
plt.plot(who_month, who_weigth_75th, color='darkorange', linewidth=1.5, linestyle='dotted', label='75th')
plt.plot(who_month, who_weigth_85th, color='orangered', linewidth=1.5, linestyle='dotted', label='85th')
plt.plot(who_month, who_weigth_95th, color='rosybrown', linewidth=1.5, linestyle='dotted', label='95th')
plt.plot(who_month, who_weigth_97th, color='brown', linewidth=1.5, linestyle='dotted', label='97th')
plt.plot(who_month, who_weigth_99th, color='red', linewidth=1.5, linestyle='dotted', label='99th')
plt.title("Weight")
plt.xlabel("Month")
plt.ylabel("Weight (kg)")
plt.margins(x=0, y=0)
plt.xticks(np.arange(min(who_month), max(who_month)+1, 1))
plt.yticks(np.arange(0, max(who_weigth_99th)+2, 1))
plt.grid(color="grey", linestyle="--", linewidth=0.25)
plt.legend(bbox_to_anchor=(-0.05, 1.05), borderaxespad=0)
plt.show()
plt.plot(month, height, color='green', linewidth=3, markevery=1, marker="o")
plt.title("Height")
plt.xlabel("Month")
plt.ylabel("Height (cm)")
plt.margins(x=0, y=0)
plt.xticks(np.arange(min(month), max(month)+2, 1))
plt.yticks(np.arange(40, max(height)+10, 10))
plt.grid(color="grey", linestyle="--", linewidth=0.5)
plt.show()
plt.plot(month, head, color='red', linewidth=3, markevery=1, marker="o")
plt.title("Head")
plt.xlabel("Month")
plt.ylabel("Head (cm)")
plt.margins(x=0, y=0)
plt.xticks(np.arange(min(month), max(month)+2, 1))
plt.yticks(np.arange(30, max(head)+5, 5))
plt.grid(color="grey", linestyle="--", linewidth=0.5)
plt.show()