import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
# Sepehr Data
month=[0, 4, 5, 8, 9, 12, 15, 18, 21, 24]
weight=[2.48, 6.4, 7.74, 8.8, 9.25, 9.74, 10.9, 11.4, 11.76, 13.2]
height=[50, 63, 68, 71, 74, 78, 81.5, 85, 86, 92.5]
head=[32, 39.5, 41.5, 43, 44, 45, 46, 46.5, 47, 48]
# WHO Weight Data + WHO Month
who_weight_data=pd.read_excel(r'D:\Documents\Growth Tracker Project\wfa-boys-0-2.xlsx', nrows=25)
who_weight_month_df=pd.DataFrame(who_weight_data, columns=['month'])
who_month=who_weight_month_df.to_numpy()
who_weight_1st_df=pd.DataFrame(who_weight_data, columns=['1st'])
who_weight_1st=who_weight_1st_df.to_numpy()
who_weight_3rd_df=pd.DataFrame(who_weight_data, columns=['3rd'])
who_weight_3rd=who_weight_3rd_df.to_numpy()
who_weight_5th_df=pd.DataFrame(who_weight_data, columns=['5th'])
who_weight_5th=who_weight_5th_df.to_numpy()
who_weight_15th_df=pd.DataFrame(who_weight_data, columns=['15th'])
who_weight_15th=who_weight_15th_df.to_numpy()
who_weight_25th_df=pd.DataFrame(who_weight_data, columns=['25th'])
who_weight_25th=who_weight_25th_df.to_numpy()
who_weight_50th_df=pd.DataFrame(who_weight_data, columns=['50th'])
who_weight_50th=who_weight_50th_df.to_numpy()
who_weight_75th_df=pd.DataFrame(who_weight_data, columns=['75th'])
who_weight_75th=who_weight_75th_df.to_numpy()
who_weight_85th_df=pd.DataFrame(who_weight_data, columns=['85th'])
who_weight_85th=who_weight_85th_df.to_numpy()
who_weight_95th_df=pd.DataFrame(who_weight_data, columns=['95th'])
who_weight_95th=who_weight_95th_df.to_numpy()
who_weight_97th_df=pd.DataFrame(who_weight_data, columns=['97th'])
who_weight_97th=who_weight_97th_df.to_numpy()
who_weight_99th_df=pd.DataFrame(who_weight_data, columns=['99th'])
who_weight_99th=who_weight_99th_df.to_numpy()
# Weight Plots
plt.plot(month, weight, color='blue', linewidth=3, markevery=1, marker="o", label='Sepehr')
plt.plot(who_month, who_weight_1st, color='red', linewidth=1.5, linestyle='dotted', label='1st')
plt.plot(who_month, who_weight_3rd, color='brown', linewidth=1.5, linestyle='dotted', label='3rd')
plt.plot(who_month, who_weight_5th, color='rosybrown', linewidth=1.5, linestyle='dotted', label='5th')
plt.plot(who_month, who_weight_15th, color='orangered', linewidth=1.5, linestyle='dotted', label='15th')
plt.plot(who_month, who_weight_25th, color='darkorange', linewidth=1.5, linestyle='dotted', label='25th')
plt.plot(who_month, who_weight_50th, color='forestgreen', linewidth=1.5, linestyle='dotted', label='50th')
plt.plot(who_month, who_weight_75th, color='darkorange', linewidth=1.5, linestyle='dotted', label='75th')
plt.plot(who_month, who_weight_85th, color='orangered', linewidth=1.5, linestyle='dotted', label='85th')
plt.plot(who_month, who_weight_95th, color='rosybrown', linewidth=1.5, linestyle='dotted', label='95th')
plt.plot(who_month, who_weight_97th, color='brown', linewidth=1.5, linestyle='dotted', label='97th')
plt.plot(who_month, who_weight_99th, color='red', linewidth=1.5, linestyle='dotted', label='99th')
plt.title("Weight")
plt.xlabel("Age (Month)")
plt.ylabel("Weight (kg)")
plt.margins(x=0, y=0)
plt.xticks(np.arange(min(who_month), max(who_month)+1, 1))
plt.yticks(np.arange(0, max(who_weight_99th)+2, 1))
plt.grid(color="grey", linestyle="--", linewidth=0.25)
plt.legend(bbox_to_anchor=(-0.05, 1.05), borderaxespad=0)
plt.show()
# WHO Height Data
who_height_data=pd.read_excel(r'D:\Documents\Growth Tracker Project\lfa-boys-0-2.xlsx', nrows=25)
who_height_1st_df=pd.DataFrame(who_height_data, columns=['1st'])
who_height_1st=who_height_1st_df.to_numpy()
who_height_3rd_df=pd.DataFrame(who_height_data, columns=['3rd'])
who_height_3rd=who_height_3rd_df.to_numpy()
who_height_5th_df=pd.DataFrame(who_height_data, columns=['5th'])
who_height_5th=who_height_5th_df.to_numpy()
who_height_15th_df=pd.DataFrame(who_height_data, columns=['15th'])
who_height_15th=who_height_15th_df.to_numpy()
who_height_25th_df=pd.DataFrame(who_height_data, columns=['25th'])
who_height_25th=who_height_25th_df.to_numpy()
who_height_50th_df=pd.DataFrame(who_height_data, columns=['50th'])
who_height_50th=who_height_50th_df.to_numpy()
who_height_75th_df=pd.DataFrame(who_height_data, columns=['75th'])
who_height_75th=who_height_75th_df.to_numpy()
who_height_85th_df=pd.DataFrame(who_height_data, columns=['85th'])
who_height_85th=who_height_85th_df.to_numpy()
who_height_95th_df=pd.DataFrame(who_height_data, columns=['95th'])
who_height_95th=who_height_95th_df.to_numpy()
who_height_97th_df=pd.DataFrame(who_height_data, columns=['97th'])
who_height_97th=who_height_97th_df.to_numpy()
who_height_99th_df=pd.DataFrame(who_height_data, columns=['99th'])
who_height_99th=who_height_99th_df.to_numpy()
# Height Plots
plt.plot(month, height, color='red', linewidth=3, markevery=1, marker="o", label='Sepehr')
plt.plot(who_month, who_height_1st, color='red', linewidth=1.5, linestyle='dotted', label='1st')
plt.plot(who_month, who_height_3rd, color='brown', linewidth=1.5, linestyle='dotted', label='3rd')
plt.plot(who_month, who_height_5th, color='rosybrown', linewidth=1.5, linestyle='dotted', label='5th')
plt.plot(who_month, who_height_15th, color='orangered', linewidth=1.5, linestyle='dotted', label='15th')
plt.plot(who_month, who_height_25th, color='darkorange', linewidth=1.5, linestyle='dotted', label='25th')
plt.plot(who_month, who_height_50th, color='forestgreen', linewidth=1.5, linestyle='dotted', label='50th')
plt.plot(who_month, who_height_75th, color='darkorange', linewidth=1.5, linestyle='dotted', label='75th')
plt.plot(who_month, who_height_85th, color='orangered', linewidth=1.5, linestyle='dotted', label='85th')
plt.plot(who_month, who_height_95th, color='rosybrown', linewidth=1.5, linestyle='dotted', label='95th')
plt.plot(who_month, who_height_97th, color='brown', linewidth=1.5, linestyle='dotted', label='97th')
plt.plot(who_month, who_height_99th, color='red', linewidth=1.5, linestyle='dotted', label='99th')
plt.title("Height")
plt.xlabel("Age (Month)")
plt.ylabel("Height (cm)")
plt.margins(x=0, y=0)
plt.xticks(np.arange(min(who_month), max(who_month)+1, 1))
plt.yticks(np.arange(40, max(who_height_99th)+10, 10))
plt.grid(color="grey", linestyle="--", linewidth=0.25)
plt.legend(bbox_to_anchor=(-0.05, 1.05), borderaxespad=0)
plt.show()
# WHO Head Data
who_head_data=pd.read_excel(r'D:\Documents\Growth Tracker Project\hfa-boys-0-2.xlsx', nrows=25)
who_head_1st_df=pd.DataFrame(who_head_data, columns=['1st'])
who_head_1st=who_head_1st_df.to_numpy()
who_head_3rd_df=pd.DataFrame(who_head_data, columns=['3rd'])
who_head_3rd=who_head_3rd_df.to_numpy()
who_head_5th_df=pd.DataFrame(who_head_data, columns=['5th'])
who_head_5th=who_head_5th_df.to_numpy()
who_head_15th_df=pd.DataFrame(who_head_data, columns=['15th'])
who_head_15th=who_head_15th_df.to_numpy()
who_head_25th_df=pd.DataFrame(who_head_data, columns=['25th'])
who_head_25th=who_head_25th_df.to_numpy()
who_head_50th_df=pd.DataFrame(who_head_data, columns=['50th'])
who_head_50th=who_head_50th_df.to_numpy()
who_head_75th_df=pd.DataFrame(who_head_data, columns=['75th'])
who_head_75th=who_head_75th_df.to_numpy()
who_head_85th_df=pd.DataFrame(who_head_data, columns=['85th'])
who_head_85th=who_head_85th_df.to_numpy()
who_head_95th_df=pd.DataFrame(who_head_data, columns=['95th'])
who_head_95th=who_head_95th_df.to_numpy()
who_head_97th_df=pd.DataFrame(who_head_data, columns=['97th'])
who_head_97th=who_head_97th_df.to_numpy()
who_head_99th_df=pd.DataFrame(who_head_data, columns=['99th'])
who_head_99th=who_head_99th_df.to_numpy()
# Head Plots
plt.plot(month, head, color='green', linewidth=3, markevery=1, marker="o", label='Sepehr')
plt.plot(who_month, who_head_1st, color='red', linewidth=1.5, linestyle='dotted', label='1st')
plt.plot(who_month, who_head_3rd, color='brown', linewidth=1.5, linestyle='dotted', label='3rd')
plt.plot(who_month, who_head_5th, color='rosybrown', linewidth=1.5, linestyle='dotted', label='5th')
plt.plot(who_month, who_head_15th, color='orangered', linewidth=1.5, linestyle='dotted', label='15th')
plt.plot(who_month, who_head_25th, color='darkorange', linewidth=1.5, linestyle='dotted', label='25th')
plt.plot(who_month, who_head_50th, color='forestgreen', linewidth=1.5, linestyle='dotted', label='50th')
plt.plot(who_month, who_head_75th, color='darkorange', linewidth=1.5, linestyle='dotted', label='75th')
plt.plot(who_month, who_head_85th, color='orangered', linewidth=1.5, linestyle='dotted', label='85th')
plt.plot(who_month, who_head_95th, color='rosybrown', linewidth=1.5, linestyle='dotted', label='95th')
plt.plot(who_month, who_head_97th, color='brown', linewidth=1.5, linestyle='dotted', label='97th')
plt.plot(who_month, who_head_99th, color='red', linewidth=1.5, linestyle='dotted', label='99th')
plt.title("Head")
plt.xlabel("Age (Month)")
plt.ylabel("Head (cm)")
plt.margins(x=0, y=0)
plt.xticks(np.arange(min(who_month), max(who_month)+1, 1))
plt.yticks(np.arange(30, max(who_head_99th)+5, 5))
plt.grid(color="grey", linestyle="--", linewidth=0.25)
plt.legend(bbox_to_anchor=(-0.05, 1.05), borderaxespad=0)
plt.show()
