# Python scripts: This program only test input/outputs.
print('Hello World!')
print('Please Type Your Name')
yourName=input()
print('Your Name is '+yourName+'.')
print('The Length of your name is:')
print(len(yourName))
print('What is your age?')
yourAge=input()
print('Your will be '+str(int(yourAge)+1)+ ' in a year.')
